services:
  app:
    container_name: app
    image: registry.sedrehgroup.ir/geodjango:latest

    ports:
      - "8000:8000"
    restart: 'always'
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - main
    volumes:
      - ./backend:/app  



  db:
    container_name: database
    image: registry.sedrehgroup.ir/postgis:16-3.4-alpine 
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - main


  pgadmin:
        container_name : pgadmin
        image: registry.sedrehgroup.ir/pgadmin4
        ports : 
          -  '5050:80'
        env_file:
          - .env
        networks:
          - main
networks:
  main:


